language: php

php:
  - 5.5
  - 5.4
  - 5.3

env:
  global:
    - PLUGIN_NAME=AdvancedCampaignReporting
  matrix:
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL

script: ./travis.sh

install:
  - mkdir $PLUGIN_NAME
  - cp -R !($PLUGIN_NAME) $PLUGIN_NAME
  - cp -R .git/ $PLUGIN_NAME/
  - git clone https://github.com/piwik/piwik.git piwik --depth=1
  - cd piwik
  - git checkout master
  - git submodule init
  - git submodule update || true
  - composer self-update
  - composer install
  - rm -rf plugins/$PLUGIN_NAME
  - cd ../
  - mv $PLUGIN_NAME piwik/plugins

before_script:
  - cd piwik
  - uname -a
  - date
  - mysql -e 'create database piwik_tests;'
  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - cd tests/PHPUnit

after_script:
  - cd ../..
  - cat /var/log/nginx/error.log
  - cat ./tmp/php-fpm.log
  - cat ./tmp/logs/piwik.log
  - ./tests/travis/upload_artifacts.sh
